@extends('layouts.app')
@section('content')
@include('layouts.header')
<style>
    
    .border-all {
        border: 1px solid #000;
    }
    .border-bottom {
        border-bottom: 1px solid #000;
    }
    .label {
        font-weight: 600;
    }
    .small-text {
        font-size: 13px;
    }
    
    .importantRule { 
        display: none !important;  /* Force hide anything with this class */
    }
    @page {
   size: A4;
   margin: 5mm 5mm 5mm 5mm; /* top right bottom left */
}

</style>

<div class="list-of-view-company ">
    <section class="list-of-view-company-section container-fluid">
        <div class="row vh-100">
            @include('layouts.leftnav')
            <div class="col-md-12 ml-sm-auto  col-lg-9 px-md-4 bg-mint">
                <div class="container my-4 border-all p-3">
                    <button class="btn btn-info header-section" onclick="printpage();">Print</button>
                    <!-- Header -->
                    <div class="row border-bottom pb-2 mb-2">
                        <div class="col-12 text-center">
                            <h5 class="mb-2 text-center">e-Way Bill</h5>
                        </div>
                        <div class="col-8">
                            <div class="small-text">
                                <div><span class="label">Doc No : </span> Tax Invoice - {{$sale->voucher_no_prefix}}</div>
                                <div><span class="label">Date : </span> {{date('d-m-Y',strtotime($sale->date))}}</div>
                                @php 
                                    $qrContent = "";
                                    $Irn = "";
                                    $AckNo = "";
                                    $AckDt = "";
                                @endphp
                                @if($sale->e_invoice_status==1 && !empty($sale->einvoice_response))
                                    @php 
                                        $einvoice_data = json_decode($sale->einvoice_response); 
                                        $qrContent = $einvoice_data->SignedQRCode;
                                        $Irn = $einvoice_data->Irn;
                                        $AckNo = $einvoice_data->AckNo;
                                        $AckDt = $einvoice_data->AckDt;
                                        $AckDt = date('d-m-Y H:i:s',strtotime($AckDt));
                                    @endphp
                                @endif
                                <div><span class="label">IRN : </span> {{$Irn}}</div>
                                <div><span class="label">Ack No : </span> {{$AckNo}}</div>
                                <div><span class="label">Ack Date : </span> {{$AckDt}}</div>
                            </div>
                        </div>
                        <div class="col-4 text-end">
                            @if(!empty($qrContent))
                                {!! QrCode::size(90)->generate($qrContent) !!}
                            @endif
                            
                            
                        </div>
                    </div>
                    <!-- 1. e-Way Bill Details -->
                    <div class="border-bottom mb-2 pb-2">
                        <div class="fw-bold mb-1">1. e-Way Bill Details</div>
                        <div class="row small-text">
                            @php $ewaybill_no = "";$ewayBillDate = "";$validUpto = ""; @endphp
                            @if($sale->e_waybill_status==1 && $sale->eway_bill_response && !empty($sale->eway_bill_response))
                                @php 
                                    $ewaybill_data = json_decode($sale->eway_bill_response);
                                    $ewaybill_no = $ewaybill_data->ewayBillNo;
                                    $ewayBillDate = $ewaybill_data->ewayBillDate;
                                    $validUpto = $ewaybill_data->validUpto;
                                @endphp
                            @endif
                            <div class="col-md-4"><span class="label">e-Way Bill No : </span> {{$ewaybill_no}}</div>
                            <div class="col-md-4"><span class="label">Mode:</span> Road</div>
                            <div class="col-md-4"><span class="label">Generated Date : </span> {{date('d-m-Y h:i a', strtotime($ewayBillDate));}}</div>
                            <div class="col-md-4"><span class="label">Generated By : </span> {{$sale->merchant_gst}}</div>
                            <div class="col-md-4"><span class="label">Approx Distance : </span> {{$sale->e_waybill_distance}} KM</div>
                            <div class="col-md-4"><span class="label">Valid Upto : </span>{{date('d-m-Y h:i a', strtotime($validUpto));}}</div>
                            <div class="col-md-4"><span class="label">Supply Type : </span> Outward Supply</div>
                            <div class="col-md-4"><span class="label">Transaction Type : </span> Regular</div>
                        </div>
                    </div>
                    <!-- 2. Address Details -->
                    <div class="border-bottom mb-2 pb-2">
                        <div class="fw-bold mb-1">2. Address Details</div>
                        <div class="row small-text">
                            <div class="col-md-6">
                                <div class="label">From</div>
                                {{$company_data->company_name}}<br>
                                GSTIN: {{ $seller_info->gst_no }}<br>
                                {{ $seller_info->sname }}
                            </div>
                            <div class="col-md-6">
                                <div class="label">To</div>
                                {{$sale->billing_name}}<br>
                                GSTIN: {{$sale->billing_gst}}<br>
                                {{$sale->billing_address}}
                            </div>

                            <div class="col-md-6 mt-2">
                                <div class="label">Dispatch From</div>
                                {{ $seller_info->address }},<br>
                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="label">Ship To</div>
                                @if($sale->shipping_name)
                                    {{$sale->shipping_address}}
                                @else                                    
                                    {{$sale->billing_address}}
                                @endif
                            </div>
                        </div>
                    </div>

                    <!-- 3. Goods Details -->
                    <div class="border-bottom mb-2 pb-2">
                        <div class="fw-bold mb-1">3. Goods Details</div>
                        <table class="table table-bordered table-sm small-text mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th>HSN Code</th>
                                    <th>Product Name & Description</th>
                                    <th class="text-end">Quantity</th>
                                    <th class="text-end">Taxable Amt</th>
                                    <th class="text-center">Tax Rate (
                                            @foreach($sale_sundry as $sundry)
                                                @if($sundry->nature_of_sundry === 'CGST')
                                                    C+S
                                                @elseif($sundry->nature_of_sundry === 'IGST')
                                                    I
                                                @endif
                                            @endforeach
                                        )</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $item_total = 0; @endphp
                                @foreach($items_detail as $item)
                                    <tr>
                                        <td>{{$item->hsn_code}}</td>
                                        <td>{{$item->items_name}}</td>
                                        <td class="text-end">{{$item->qty}} {{$item->unit}}</td>
                                        <td class="text-end">{{formatIndianNumber($item->amount)}}</td>
                                        <td class="text-center">
                                            @php
                                                $rates = $sale_sundry->where('rate', '!=', 0)->pluck('rate')->toArray();
                                            @endphp
                                            {{ implode(' + ', $rates) }}
                                        </td>
                                    </tr>
                                    @php $item_total = $item_total + $item->amount; @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- Totals -->
                    <div class="border-bottom mb-2 pb-2 small-text">
                        <div class="row">
                            <div class="col-md-4"><span class="label">Total Taxable Amt:</span> {{$item_total}}</div>
                            @foreach($sale_sundry as $sundry)
                                @if($sundry->nature_of_sundry === 'CGST')
                                    <div class="col-md-4"><span class="label">CGST Amt : </span> {{$sundry->amount}}</div>
                                    <div class="col-md-4"><span class="label">SGST Amt : </span> {{$sundry->amount}}</div>
                                @elseif($sundry->nature_of_sundry === 'IGST')
                                    <div class="col-md-4"><span class="label">IGST Amt : </span> {{$sundry->amount}}</div>
                                    <div class="col-md-4"><span class="label"></div>
                                @endif
                            @endforeach
                        </div>
                        <div class="row mt-1">
                            <div class="col-md-4"><span class="label">Other Amt:</span> 
                                  
                                @foreach($sale_sundry as $sundry)
                                    @if($sundry->nature_of_sundry === 'ROUNDED OFF (+)' || $sundry->nature_of_sundry === 'ROUNDED OFF (-)')
                                        @if($sundry->bill_sundry_type === 'additive')
                                            (+){{$sundry->amount}}
                                        @elseif($sundry->bill_sundry_type === 'subtractive')
                                            (-){{$sundry->amount}}
                                        @endif
                                    @endif
                                @endforeach
                                </div>
                            <div class="col-md-4"></div>
                            <div class="col-md-4 fw-bold"><span class="label">Total Inv Amt:</span> {{formatIndianNumber($sale->total)}}</div>
                        </div>
                    </div>

                    <!-- 4. Transportation Details -->
                    <div class="border-bottom mb-2 pb-2 small-text">
                        <div class="fw-bold mb-1">4. Transportation Details</div>
                        <div class="row">
                            <div class="col-md-6"><span class="label">Transporter ID:</span></div>
                            <div class="col-md-6"><span class="label">Doc No : </span>{{$sale->gr_pr_no}}</div>
                            <div class="col-md-6"><span class="label">Name : </span>{{$sale->transport_name}}</div>
                            <div class="col-md-6"><span class="label">Date : </span> {{date('d-m-Y',strtotime($sale->date))}}</div>
                        </div>
                    </div>

                    <!-- 5. Vehicle Details -->
                    <div class="small-text">
                        <div class="fw-bold mb-1">5. Vehicle Details</div>
                        <div class="row">
                            <div class="col-md-4"><span class="label">Vehicle No : </span> {{$sale->vehicle_no}}</div>
                            <div class="col-md-4"><span class="label">From : UNA BATHRI</span></div>
                            <div class="col-md-4"><span class="label">CEWB No : </span></div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>
@include('layouts.footer')
<script>
    function printpage(){
        $('.header-section').addClass('importantRule');
        $('.sidebar').addClass('importantRule');
        window.print();
        $('.header-section').removeClass('importantRule');
        $('.sidebar').removeClass('importantRule');
    }
</script>
@endsection

