<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\company\CompanyController;
use App\Http\Controllers\company\OwnerController;
use App\Http\Controllers\company\ShareholderController;
use App\Http\Controllers\company\BankController;
use App\Http\Controllers\heading\AccountHeadingController;
use App\Http\Controllers\group\AccountGroupsController;
use App\Http\Controllers\unit\UnitsController;
use App\Http\Controllers\itemgroup\ItemGroupsController;
use App\Http\Controllers\manageitem\ManageItemsController;
use App\Http\Controllers\billsundry\BillSundrysController;
use App\Http\Controllers\account\AccountsController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\SalesReturnController;
use App\Http\Controllers\PurchaseReturnController;
use App\Http\Controllers\journal\JournalController;
use App\Http\Controllers\receipt\ReceiptController;
use App\Http\Controllers\contra\ContraController;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\payment\PaymentController;
use App\Http\Controllers\dashboard\GstSettingController;
use App\Http\Controllers\display\BalanceSheetController;
use App\Http\Controllers\display\ProfitLossController;
use App\Http\Controllers\display\TrialBalanceController;
use App\Http\Controllers\accountledger\AccountLedgerController;
use App\Http\Controllers\ItemLedgerController;
use App\Http\Controllers\display\CurrentLiabilitiesController;
use App\Http\Controllers\display\DutyTaxController;
use App\Http\Controllers\display\DisplayCgstController;
use App\Http\Controllers\MerchantEmployeeController;
use App\Http\Controllers\AdminModuleController\DashboradController;
use App\Http\Controllers\AdminModuleController\MerchantController;
use App\Http\Controllers\manageitem\ItemParameterizedController;
use App\Http\Controllers\CreditNoteWithoutItemController;
use App\Http\Controllers\DebitNoteWithoutItemController;
use App\Http\Controllers\AdminModuleController\AccountHeadController;
use App\Http\Controllers\AdminModuleController\AccountGroupController;
use App\Http\Controllers\AdminModuleController\AccountController;
use App\Http\Controllers\AdminModuleController\MerchantPrivilegesController;
use App\Http\Controllers\AdminModuleController\MerchantModulePermissionController;
use App\Http\Controllers\VoucherSeriesConfigurationController;
use App\Http\Controllers\StockTransfer\StockTransferController;
use App\Http\Controllers\gstReturn\gstR1Controller;
use App\Http\Controllers\gstReturn\GstDetailController;
use App\Http\Controllers\gstReturn\GSTR2BController;
use App\Http\Controllers\gstReturn\GSTR2AController;
use App\Http\Controllers\gstReturn\GSTR3BController;
use App\Http\Controllers\ParameterizedStockController;
use App\Http\Controllers\saleOrder\SaleOrderController;
use App\Http\Controllers\Supplier\SupplierController;
use App\Http\Controllers\Supplier\SupplierRateLocationWiseController;
use App\Http\Controllers\Supplier\SupplierPurchaseController;
use App\Http\Controllers\Supplier\SupplierSubHeadController;
use App\Http\Controllers\AdminModuleController\ManageUserController;
use App\Http\Controllers\AdminModuleController\AdminPrivilegesController;
use App\Http\Controllers\deal\DealController;
use App\Http\Controllers\Supplier\FuelSupplierController;
use App\Http\Controllers\SaleRegisterController;
use App\Http\Controllers\PurchaseRegisterController;
use App\Http\Controllers\production\ProductionController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Route::get('/', function () {
    return view('welcome');
});*/
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
//Route::prefix('admin')->name('admin.')->group(function(){
   Route::get('/',[AdminAuthController::class, 'index'])->name('password.login');
   Route::post('/login',[AdminAuthController::class, 'adminLogin'])->name('login');
   Route::group(['middleware' => ['adminAuth']], function() {
      Route::get('/dashboard',[DashboradController::class, 'index'])->name('dashboard');
      Route::get('/logout',[AdminAuthController::class, 'logout'])->name('logout');
      Route::get('/change-password-view',[AdminAuthController::class, 'changePasswordView'])->name('change-password-view');
      Route::post('/change-password-update',[AdminAuthController::class, 'changePasswordUpdate'])->name('change-password-update');
      Route::Resource('/merchant',MerchantController::class)->name('*','merchant');
      Route::Resource('/account-head',AccountHeadController::class)->name('*','account-head');
      Route::Resource('/account-group',AccountGroupController::class)->name('*','account-group');
      Route::Resource('/account',AccountController::class)->name('*','account');
      Route::post('/login-merchant', [MerchantController::class, 'loginMerchant']);
      Route::Resource('/merchant-privilege',MerchantPrivilegesController::class)->name('*','merchant-privilege');
      Route::get('/merchant-module-permission/{id?}',[MerchantModulePermissionController::class, 'index'])->name('merchant-module-permission');
      Route::post('/store-merchant-module',[MerchantModulePermissionController::class, 'storeMerchantModule'])->name('store-merchant-module');
      Route::resource('manageUser', ManageUserController::class);
      Route::get('manage-users', [ManageUserController::class,'index'])->name('manageUser.index');
      Route::get('manage-users/create', [ManageUserController::class,'create'])->name('manageUser.create');
      Route::post('manage-users/store', [ManageUserController::class,'store'])->name('manageUser.store');
      Route::get('manage-users/{id}/edit', [ManageUserController::class,'edit'])->name('manageUser.edit');
      Route::put('manage-users/{id}/update', [ManageUserController::class,'update'])->name('manageUser.update');
      Route::delete('manage-users/{id}', [ManageUserController::class, 'destroy'])->name('manageUser.destroy');
      Route::get('manage-users/{id}/privileges', [ManageUserController::class,'privileges'])->name('manageUser.privileges');
      Route::post('manage-users/set-privileges', [ManageUserController::class,'setUserPrivileges'])->name('manageUser.setUserPrivileges');
      Route::get('manage-users/{id}/assign-companies', [ManageUserController::class, 'assignCompanies'])->name('manageUser.assignCompanies');
      Route::post('manage-users/assign-companies', [ManageUserController::class, 'storeAssignCompanies'])->name('manageUser.storeAssignCompanies');
      Route::resource('/admin-privilege', AdminPrivilegesController::class)->name('*','admin-privilege');
      Route::get('manage-users/{id}/admin-privileges', [ManageUserController::class, 'adminPrivileges'])->name('manageUser.adminPrivileges');
      Route::post('manage-users/{id}/admin-privileges/save', [ManageUserController::class, 'saveAdminPrivileges'])->name('manageUser.saveAdminPrivileges');

 });
});

Route::get('/', [AuthController::class, 'index'])->name('password.login');
Route::get('password-login', [AuthController::class, 'index'])->name('password.login');
Route::get('forgot-password', [AuthController::class, 'forgotPassword'])->name('password.forgot');
Route::post('forgot-otp', [AuthController::class, 'forgotOtp'])->name('forgot.otp');
Route::post('forgot-otp-login', [AuthController::class, 'changePassword'])->name('submit.forgototp');
Route::get('otp-login', [AuthController::class, 'otpLogin'])->name('otp.login');
Route::post('otp-generate', [AuthController::class, 'generate'])->name('otp.generate');
Route::post('submit-otp-login', [AuthController::class, 'loginWithOtp'])->name('submit.otplogin');
Route::post('password-login-check', [AuthController::class, 'passwordLoginCheck'])->name('password.login-check');
Route::get('registration', [AuthController::class, 'registration'])->name('register.user');
Route::post('register', [AuthController::class, 'register'])->name('register');
Route::post('send-otp', [AuthController::class, 'sendOtp'])->name('send-otp');
Route::post('verify-otp', [AuthController::class, 'verifyOtp'])->name('verify-otp');
Route::post('change-otp-verify-status', [AuthController::class, 'changeOtpVerifyStatus'])->name('change-otp-verify-status');
Route::post('change-password', [AuthController::class, 'submitChangePassword'])->name('password.changepassword');
Route::group(['middleware' => ['merchantloginstatus']], function () {
   Route::get('change-password-view', [AuthController::class, 'changePasswordView'])->name('change-password-view');
   Route::post('change-password-update', [AuthController::class, 'changePasswordUpdate'])->name('change-password-update');
   Route::get('dashboard', [AuthController::class, 'dashboard'])->name('dashboard');
   Route::post('change-company', [AuthController::class, 'changeCompany'])->name('company.change');
   Route::get('logout', [AuthController::class, 'logout'])->name('logout');
   Route::get('view-company', [CompanyController::class, 'viewCompany'])->name('view-company');
   Route::get('manage-financial-year', [CompanyController::class, 'manageFinancialYear'])->name('manage-financial-year');
   Route::post('change-financial-year', [CompanyController::class, 'changeDefaultFY'])->name('change-financial-year');
   Route::get('company-listing', [CompanyController::class, 'companyListing'])->name('company-listing');
   Route::get('add-company', [CompanyController::class, 'addCompany'])->name('add-company');
   Route::post('check-gst', [CompanyController::class, 'checkGst'])->name('check-gst');
   Route::post('submit-add-company', [CompanyController::class, 'submitAddCompany'])->name('submit-add-company');
   Route::post('submit-edit-company', [CompanyController::class, 'submitEditCompany'])->name('submit-edit-company');
   Route::get('add-owner', [OwnerController::class, 'addOwner'])->name('add-owner');
   Route::post('submit-add-owner', [OwnerController::class, 'submitAddOwner'])->name('submit-add-owner');
   Route::post('submit-delete-owner', [OwnerController::class, 'submitDeleteOwner'])->name('submit-delete-owner');
   Route::get('add-shareholder', [ShareholderController::class, 'addShareholder'])->name('add-shareholder');
   Route::post('submit-add-shareholder', [ShareholderController::class, 'submitAddShareholder'])->name('submit-add-shareholder');
   Route::get('add-bank', [BankController::class, 'addBank'])->name('add-bank');
   Route::post('submit-add-bank', [BankController::class, 'submitAddBank'])->name('submit-add-bank');
   Route::post('delete-bank', [BankController::class, 'deleteBank'])->name('delete-bank');
   Route::get('company-edit', [CompanyController::class, 'companyEdit'])->name('company.company-edit');
   Route::get('owner-edit/{id}', [OwnerController::class, 'ownerEdit'])->name('owner.owner-edit');
   Route::get('shareholder-edit/{id}', [ShareholderController::class, 'shareholderEdit'])->name('shareholder.shareholder-edit');
   Route::get('bank-edit/{id}', [BankController::class, 'bankEdit'])->name('shareholder.shareholder-edit');
   Route::get('view-owner/{id}', [OwnerController::class, 'viewOwner'])->name('view-owner');
   Route::get('view-shareholder/{id}', [ShareholderController::class, 'viewShareholder'])->name('view-shareholder');
   Route::get('view-bank/{id}', [BankController::class, 'viewBank'])->name('view-bank');
   Route::post('submit-edit-owner', [OwnerController::class, 'update'])->name('submit-edit-owner.update');
   Route::post('submit-edit-shareholder', [ShareholderController::class, 'update'])->name('submit-edit-shareholder.update');
   Route::post('submit-edit-bank', [BankController::class, 'update'])->name('submit-edit-bank.update');
   //AccountHeading CRUD
   Route::Resource('account', AccountsController::class);
   Route::get('add-account', [AccountsController::class, 'addAccount']);
   Route::post('account-update', [AccountsController::class, 'update'])->name('account.update');
   Route::post('account-delete', [AccountsController::class, 'delete'])->name('account.delete');
   Route::get('import-account-view', [AccountsController::class, 'importAccountView'])->name('import-account-view');
   Route::post('import-account-process', [AccountsController::class, 'importAccountProcess'])->name('import-account-process');
   Route::Resource('account-heading', AccountHeadingController::class);
   Route::post('account-heading-update', [AccountHeadingController::class, 'update'])->name('account-heading.update');
   Route::post('account-heading-delete', [AccountHeadingController::class, 'delete'])->name('account-heading.delete');
   Route::Resource('account-group', AccountGroupsController::class);
   Route::post('account-group-update', [AccountGroupsController::class, 'update'])->name('account-group.update');
   Route::post('account-group-delete', [AccountGroupsController::class, 'delete'])->name('account-group.delete');
   Route::Resource('account-unit', UnitsController::class);
   Route::post('account-unit-update', [UnitsController::class, 'update'])->name('account-unit.update');
   Route::post('account-unit-delete', [UnitsController::class, 'delete'])->name('account-unit.delete');
   Route::Resource('account-item-group', ItemGroupsController::class);
   Route::post('account-item-group-update', [ItemGroupsController::class, 'update'])->name('account-item-group.update');
   Route::post('account-item-group-delete', [ItemGroupsController::class, 'delete'])->name('account-item-group.delete');
   Route::Resource('account-manage-item', ManageItemsController::class);
   Route::post('account-manage-item-update', [ManageItemsController::class, 'update'])->name('account-manage-item.update');
   Route::get('stock-journal', [ManageItemsController::class, 'stockJournal'])->name('stock-journal');
   Route::get('add-stock-journal', [ManageItemsController::class, 'addStockJournal'])->name('add-stock-journal');
   Route::post('save-stock-journal', [ManageItemsController::class, 'saveStockJournal'])->name('save-stock-journal');
   Route::post('delete-stock-journal', [ManageItemsController::class, 'deleteStockJournal'])->name('delete-stock-journal');
   Route::get('edit-stock-journal/{id}', [ManageItemsController::class, 'editStockJournal']);
   Route::post('update-stock-journal', [ManageItemsController::class, 'updateStockJournal'])->name('update-stock-journal');
   Route::post('account-manage-item-delete', [ManageItemsController::class, 'delete'])->name('account-manage-item.delete');
   Route::get('item-import-view', [ManageItemsController::class, 'itemImportView'])->name('item-import-view');
   Route::post('item-import-process', [ManageItemsController::class, 'itemImportProcess'])->name('item-import-process');

   Route::Resource('account-bill-sundry', BillSundrysController::class);
   Route::post('account-bill-sundry-update', [BillSundrysController::class, 'update'])->name('account-bill-sundry.update');
   Route::post('account-bill-sundry-delete', [BillSundrysController::class, 'delete'])->name('account-bill-sundry.delete');
   Route::Resource('purchase', PurchaseController::class);
   Route::post('purchase-update', [PurchaseController::class, 'update'])->name('purchase.update');
   Route::post('purchase-delete', [PurchaseController::class, 'delete'])->name('purchase.delete');
   Route::get('purchase-invoice/{id:?}', [PurchaseController::class, 'purchaseInvoice'])->name('purchase-invoice');
   Route::get('purchase-edit/{id}', [PurchaseController::class, 'purchaseEdit']);
   Route::get('purchase-import-view', [PurchaseController::class, 'purchaseImportView'])->name('purchase-import-view');
   Route::post('purchase-import-process', [PurchaseController::class, 'purchaseImportProcess'])->name('purchase-import-process');
   Route::post('account-manage-item-store', [SalesController::class, 'manageItemStore'])->name('account-manage-item-store');
   Route::post('account-store', [SalesController::class, 'addAccountStore'])->name('account-store');
   Route::Resource('sale', SalesController::class);
   Route::get('edit-sale/{id}', [SalesController::class, 'edit']);
   Route::post('sale-update', [SalesController::class, 'update'])->name('sale.update');
   Route::post('sale-delete', [SalesController::class, 'delete'])->name('sale.delete');
   Route::get('sale-invoice/{id:?}', [SalesController::class, 'saleInvoice'])->name('sale-invoice');
   Route::get('sale-import-view', [SalesController::class, 'saleImportView'])->name('sale-import-view');
   Route::post('sale-import-process', [SalesController::class, 'saleImportProcess'])->name('sale-import-process');
   Route::get('account-group-import-view', [AccountGroupsController::class, 'accountGroupImportView'])->name('account-group-import-view');
   Route::post('account-group-import-process', [AccountGroupsController::class, 'accountGroupImportProcess'])->name('account-group-import-process');

   Route::Resource('sale-return', SalesReturnController::class);
   Route::get('sale-return-invoice/{id:?}', [SalesReturnController::class, 'saleReturnInvoice'])->name('sale-return-invoice');
   Route::get('sale-return-without-item-invoice/{id}', [SalesReturnController::class, 'saleReturnWithoutItemInvoice']);
   Route::get('sale-return-without-gst-invoice/{id}', [SalesReturnController::class, 'saleReturnWithoutGstInvoice']);
   Route::get('sale-return-edit/{id}', [SalesReturnController::class, 'edit']);
   Route::post('sale-return-update', [SalesReturnController::class, 'update'])->name('sale-return-update');
   Route::post('sale-return-delete', [SalesReturnController::class, 'delete'])->name('sale-return.delete');
   Route::post('generate-credit-note-einvoice', [SalesReturnController::class, 'generateEinvoice'])->name('generate-credit-note-einvoice');
   Route::post('generate-credit-note-without-item-einvoice', [SalesReturnController::class, 'generateEinvoiceWithoutItem'])->name('generate-credit-note-without-item-einvoice');
   Route::post('generate-ewaybill-sale-return', [SalesReturnController::class, 'generateEinvoice'])->name('generateEwaybillSaleReturn');
   Route::post('cancel-einvoice-sale-return', [SalesReturnController::class, 'generateEinvoice'])->name('cancelEinvoiceSaleReturn');
   Route::post('cancel-ewaybill-sale-return', [SalesReturnController::class, 'cancelEwaybillSaleReturn'])->name('cancel-ewaybill-sale-return');
   Route::Resource('purchase-return', PurchaseReturnController::class);
   Route::post('purchase-return-update', [PurchaseReturnController::class, 'update'])->name('purchase-return-update');
   Route::post('purchase-return-delete', [PurchaseReturnController::class, 'delete'])->name('purchase-return.delete');
   Route::get('purchase-return-invoice/{id:?}', [PurchaseReturnController::class, 'purchaseReturnInvoice'])->name('purchase-return-invoice');
   Route::get('purchase-return-without-item-invoice/{id}', [PurchaseReturnController::class, 'purchaseReturnWithoutItemInvoice']);
   Route::get('purchase-return-without-gst-invoice/{id}', [PurchaseReturnController::class, 'purchaseReturnWithoutGstInvoice']);
   Route::get('purchase-return-vehicle-entry-detail/{id}', [PurchaseReturnController::class, 'purchaseReturnVehicleEntryDetail']);
   Route::get('purchase-return-edit/{id}', [PurchaseReturnController::class, 'edit']);
   Route::post('generate-debit-note-einvoice', [PurchaseReturnController::class, 'generateEinvoice'])->name('generate-debit-note-einvoice');
   Route::post('generate-debit-note-without-item-einvoice', [PurchaseReturnController::class, 'generateEinvoiceWithoutItem'])->name('generate-debit-note-without-item-einvoice');
   Route::post('generate-ewaybill-purchase-return', [PurchaseReturnController::class, 'generateEwaybillPurchaseReturn'])->name('generate-ewaybill-purchase-return');
   Route::post('cancel-einvoice-purchase-return', [PurchaseReturnController::class, 'cancelEinvoicePurchaseReturn'])->name('cancel-einvoice-purchase-return');
   Route::post('cancel-ewaybill-purchase-return', [PurchaseReturnController::class, 'cancelEwaybillPurchaseReturn'])->name('cancel-ewaybill-purchase-return');
   Route::Resource('payment', PaymentController::class);
   Route::post('payment-update', [PaymentController::class, 'update'])->name('payment.update');
   Route::post('payment-delete', [PaymentController::class, 'delete'])->name('payment.delete');
   Route::get('payment-import-view', [PaymentController::class, 'paymentImportView'])->name('payment-import-view');
   Route::post('payment-import-process', [PaymentController::class, 'paymentImportProcess'])->name('payment-import-process');
   Route::Resource('receipt', ReceiptController::class);
   Route::post('receipt-update', [ReceiptController::class, 'update'])->name('receipt.update');
   Route::post('receipt-delete', [ReceiptController::class, 'delete'])->name('receipt.delete');
   Route::get('receipt-import-view', [ReceiptController::class, 'receiptImportView'])->name('receipt-import-view');
   Route::post('receipt-import-process', [ReceiptController::class, 'receiptImportProcess'])->name('receipt-import-process');
   Route::Resource('journal', JournalController::class);
   Route::post('journal-update', [JournalController::class, 'update'])->name('journal.update');
   Route::post('journal-delete', [JournalController::class, 'delete'])->name('journal.delete');
   Route::get('journal-import-view', [JournalController::class, 'journalImportView'])->name('journal-import-view');
   Route::post('journal-import-process', [JournalController::class, 'journalImportProcess'])->name('journal-import-process');
   Route::Resource('contra', ContraController::class);
   Route::post('contra-update', [ContraController::class, 'update'])->name('contra.update');
   Route::post('contra-delete', [ContraController::class, 'delete'])->name('contra.delete');
   Route::get('contra-import-view', [ContraController::class, 'contraImportView'])->name('contra-import-view');
   Route::post('contra-import-process', [ContraController::class, 'contraImportProcess'])->name('contra-import-process');
   Route::Resource('gst-setting', GstSettingController::class);
   Route::post('gst-setting-update', [GstSettingController::class, 'update'])->name('gst-setting.update');
   Route::post('gst-setting-delete', [GstSettingController::class, 'delete'])->name('gst-setting.delete');
   Route::Resource('balancesheet', BalanceSheetController::class);
   Route::post('balancesheet-update', [BalanceSheetController::class, 'update'])->name('balancesheet.update');
   Route::post('balancesheet-delete', [BalanceSheetController::class, 'delete'])->name('balancesheet.delete');
   Route::get('balancesheet-filter', [BalanceSheetController::class, 'filter'])->name('balancesheet.filter');
   Route::get('group-balance-by-head/{id}/{from_date}/{to_date}', [BalanceSheetController::class, 'groupBalanceByHead']);
   Route::get('account-balance-by-group/bs/{id}/{from_date}/{to_date}/{type}', [BalanceSheetController::class, 'accountBalanceByGroup']);
   Route::Resource('profitloss', ProfitLossController::class);
   Route::post('profitloss-update', [ProfitLossController::class, 'update'])->name('profitloss.update');
   Route::post('profitloss-delete', [ProfitLossController::class, 'delete'])->name('profitloss.delete');
   Route::get('profitloss-filter', [ProfitLossController::class, 'filter'])->name('profitloss.filter');
   Route::get('sale-by-month/{financial_year:?}', [ProfitLossController::class, 'saleByMonth'])->name('sale-by-month');
   Route::get('sale-by-month-detail/{financial_year:?}/{from_date}/{to_date}/{search_type:?}', [ProfitLossController::class, 'saleByMonthDetail'])->name('sale-by-month-detail');
   Route::get('purchase-by-month/{financial_year:?}', [ProfitLossController::class, 'purchaseByMonth'])->name('purchase-by-month');
   Route::get('purchase-by-month-detail/{financial_year:?}/{from_date}/{to_date}/{search_type:?}', [ProfitLossController::class, 'purchaseByMonthDetail'])->name('purchase-by-month-detail');
   Route::get('account-balance-by-group/{id}/{financial_year}/{from_date}/{to_date}', [ProfitLossController::class, 'accountBalanceByGroup']);
   Route::get('account-monthly-summary/{id}/{financial_year}', [ProfitLossController::class, 'accountMonthlySummary']);
   Route::Resource('trialbalance', TrialBalanceController::class);
   Route::post('trialbalance-update', [TrialBalanceController::class, 'update'])->name('trialbalance.update');
   Route::post('trialbalance-delete', [TrialBalanceController::class, 'delete'])->name('trialbalance.delete');
   Route::get('trialbalance-filter', [TrialBalanceController::class, 'filter'])->name('trialbalance.filter');
   Route::Resource('accountledger', AccountLedgerController::class);
   Route::post('accountledger-update', [AccountLedgerController::class, 'update'])->name('accountledger.update');
   Route::post('accountledger-delete', [AccountLedgerController::class, 'delete'])->name('accountledger.delete');
   Route::get('accountledger-filter', [AccountLedgerController::class, 'filter'])->name('accountledger.filter');
   Route::get('/ledger/export-pdf', [AccountLedgerController::class, 'exportPdf'])->name('ledger.export.pdf');
   Route::Resource('itemledger', ItemLedgerController::class);
   Route::post('itemledger-update', [ItemLedgerController::class, 'update'])->name('itemledger.update');
   Route::post('itemledger-delete', [ItemLedgerController::class, 'delete'])->name('itemledger.delete');
   Route::get('itemledger-filter', [ItemLedgerController::class, 'filter'])->name('itemledger.filter');
   Route::get('item-ledger-average', [ItemLedgerController::class, 'itemLedgerAverage'])->name('item-ledger-average');
   Route::get('item-ledger-average-by-godown', [ItemLedgerController::class, 'itemLedgerAverageByGodown'])->name('item-ledger-average-by-godown');
   Route::Resource('currentliabilities', CurrentLiabilitiesController::class);
   Route::post('currentliabilities-update', [CurrentLiabilitiesController::class, 'update'])->name('currentliabilities.update');
   Route::post('currentliabilities-delete', [CurrentLiabilitiesController::class, 'delete'])->name('currentliabilities.delete');
   Route::Resource('dutytax', DutyTaxController::class);
   Route::post('dutytax-update', [DutyTaxController::class, 'update'])->name('dutytax.update');
   Route::post('dutytax-delete', [DutyTaxController::class, 'delete'])->name('dutytax.delete');
   Route::Resource('displaycgst', DisplayCgstController::class);
   Route::post('displaycgst-update', [DisplayCgstController::class, 'update'])->name('displaycgst.update');
   Route::post('displaycgst-delete', [DisplayCgstController::class, 'delete'])->name('displaycgst.delete');
   //User Management
   Route::Resource('manage-merchant-employee', MerchantEmployeeController::class);
   Route::get('merchant-employee-privileges/{id}',[MerchantEmployeeController::class,'employeePrivileges']);
   Route::post('set-employee-privileges',[MerchantEmployeeController::class,'setEmployeePrivileges'])->name('set-employee-privileges');
   Route::get('parameterized-configuration',[ItemParameterizedController::class,'index'])->name('parameterized-configuration');
   Route::post('store-parameterized-configuration',[ItemParameterizedController::class,'storeParameterizedConfiguration'])->name('store-parameterized-configuration');
   Route::get('voucher-series-configuration',[VoucherSeriesConfigurationController::class,'index'])->name('voucher-series-configuration');
   Route::post('add-series-configuration',[VoucherSeriesConfigurationController::class,'addSeriesConfiguration'])->name('add-series-configuration');
   Route::post('series-configuration-by-series',[VoucherSeriesConfigurationController::class,'seriesConfigurationBySeries'])->name('series-configuration-by-series');
   Route::get('sale-invoice-configuration',[SalesController::class,'saleInvoiceConfiguration'])->name('sale-invoice-configuration');
   Route::post('add-sale-invoice-configuration',[SalesController::class,'addSaleInvoiceConfiguration'])->name('add-sale-invoice-configuration');
   Route::Resource('credit-note-without-item', CreditNoteWithoutItemController::class);
   Route::Resource('debit-note-without-item', DebitNoteWithoutItemController::class);
   
   
   Route::Resource('stock-transfer', StockTransferController::class);
   //Route::get('login', [AuthController::class, 'index'])->name('otp.login');
   //Route::get('/', 'AuthController@index')->name('index');
   //Route::post('dashboard', [AuthController::class, 'dashboard']); 
   //Route::post('/', [AuthController::class, 'index'])->name('login');
   /*Route::get('login', [AuthController::class, 'index'])->name('login');
   Route::get('password-login', [AuthController::class, 'passwordLogin'])->name('password.login');
   Route::post('custom-login', [AuthController::class, 'customLogin'])->name('login.custom'); 

   Route::post('custom-registration', [AuthController::class, 'customRegistration'])->name('register.custom'); 
   Route::get('signout', [AuthController::class, 'signOut'])->name('signout');*/

   // Ajax requests
   Route::post('check-debit-credit-note-voucherno', [AjaxController::class, 'checkDebitCreditNoteVoucherno']);
   Route::post('get/items/details', [AjaxController::class, 'getItemDetails']);
   Route::post('get/billsundry/details', [AjaxController::class, 'getBillSundryDetails']);
   Route::post('get/accounts/details', [AjaxController::class, 'getAccountsDetails']);
   Route::post('get/invoice/details', [AjaxController::class, 'getInvoiceDetails']);
   Route::post('get/saleitems/details', [AjaxController::class, 'getSaleItemsDetails']);
   Route::post('get/purchaseitems/details', [AjaxController::class, 'getPurchaseItemsDetails']);
   Route::post('get/purchaseinvoice/details', [AjaxController::class, 'getPurchaseInvoiceDetails']);
   Route::post('set-redircet-url', [AjaxController::class, 'setRedircetUrl']);
   Route::post('set-primary-bank', [AjaxController::class, 'setPrimaryBank']);
   Route::post('get-party-list', [AjaxController::class, 'getPartyList']);
   Route::post('get-item-list', [AjaxController::class, 'getItemList']);
   Route::post('check-account-name', [AjaxController::class, 'checkAccountName']);
   Route::post('check-gstin', [AjaxController::class, 'checkGstin']);
   Route::post('update-item-stock', [AjaxController::class, 'updateItemStock']);
   Route::post('get-next-invoiceno', [AjaxController::class, 'getNextInvoiceno']);
   Route::post('get-next-salereturnno', [AjaxController::class, 'getNextSaleReturnno']);
   Route::post('get-next-purchasereturnno', [AjaxController::class, 'getNextPurchaseReturnno']);
   Route::post('get-parameter-data', [AjaxController::class, 'getParameterData']);
   Route::post('get-item-parameter', [AjaxController::class, 'getItemParameter']);
   Route::post('generate-einvoice', [SalesController::class, 'generateEinvoice']);
   Route::post('generate-ewaybill', [SalesController::class, 'generateEwayBill']);
   Route::post('cancel-einvoice', [SalesController::class, 'cancelEinvoice']);
   Route::post('cancel-ewaybill', [SalesController::class, 'cancelEwayBill']);
   Route::post('get-item-average-details', [ItemLedgerController::class, 'itemAverageDetails']);
   Route::get('/gstr1', [gstR1Controller::class, 'gstmain'])->name('gstr1');
   Route::get('/gst/b2c-normal-statewise', [gstR1Controller::class, 'B2Cstatewise'])->name('gst.b2c.normal.statewise');
   Route::get('/gst/b2b-detailed-billwise', [gstR1Controller::class, 'B2Bdetailed'])->name('gst.b2b.detailed.billwise');
   Route::get('/gst/b2c-large-detailed', [gstR1Controller::class, 'b2cLargedetailed'])->name('gst.b2c.large.detailed');
   Route::get('/report/filter', [gstR1Controller::class, 'filterform'])->name('report.filter.data');
   Route::get('gst2a', [GSTR2AController::class, 'index'])->name('gst2a');
   Route::post('gstr2a-detail', [GSTR2AController::class, 'gstr2aDetail'])->name('gstr2a-detail');
   Route::get('gstr2a-all-info/{month}/{gstin}/{ctin}', [GSTR2AController::class, 'gstr2aAllInfo'])->name('gstr2a-all-info');
   Route::get('parameterized-stock', [ParameterizedStockController::class,'index'])->name('parameterized-stock');  
   Route::get('gst2b', [GSTR2BController::class, 'index'])->name('gst2b');  
   Route::post('gstr2b-detail', [GSTR2BController::class, 'gstr2bDetail'])->name('gstr2b-detail');
   Route::get('gstr2b-all-info/{month}/{gstin}/{ctin}', [GSTR2BController::class, 'gstr2bAllInfo'])->name('gstr2b-all-info');
   Route::post('reject-gstr2b-entry', [GSTR2BController::class, 'rejectEntry'])->name('reject-gstr2b-entry');
   Route::post('get-unlinked-cdnr', [GSTR2BController::class, 'getUnlinkedCdnr'])->name('get-unlinked-cdnr');
   Route::post('link-cdnr', [GSTR2BController::class, 'linkCdnr'])->name('link-cdnr');
   Route::post('get-unlink-invoice-entry', [GSTR2BController::class, 'getUnlinkInvoiceEntry'])->name('get-unlink-invoice-entry');
   Route::post('link-gstr2b-invoice-entry', [GSTR2BController::class, 'linkGstr2bInvoiceEntry'])->name('link-gstr2b-invoice-entry');
   Route::get('gstr2b-reconciliation-data/{month}/{gstin}', [GSTR2BController::class, 'gstr2bReconciliationData'])->name('gstr2b-reconciliation-data');
   Route::post('gstr2b-reconciliation-detail', [GSTR2BController::class, 'gstr2bReconciliationDetail'])->name('gstr2b-reconciliation-detail');
   Route::post('accept-gstr2b-entry', [GSTR2BController::class, 'acceptGstr2bEntry'])->name('accept-gstr2b-entry');
   Route::post('verify-gst-token-otp', [AjaxController::class, 'verifyGstTokenOtp'])->name('verify-gst-token-otp');
   Route::get('/report/nilratedreginter', [gstR1Controller::class, 'nilRatedAndExemptedCombined'])->name('nilratedreginter');
   Route::get('/report/debitnote', [gstR1Controller::class, 'combinedNoteRegister'])->name('debitNote');
   Route::get('/report/debitnote/Unreg', [gstR1Controller::class, 'combinedNoteUnreegister'])->name('debitNoteUnreg');
   //  Route::get('/report/debitnote/state', [gstR1Controller::class, 'B2Cstatewise1'])->name('state');
   Route::get('/report/hsn', [gstR1Controller::class, 'hsnSummary'])->name('hsnSummary');
   Route::get('/document-summary', [gstR1Controller::class, 'documentIssuedSummary'])->name('docIssued');
   Route::get('/gstr1/view', [GstR1Controller::class, 'showView'])->name('gstr1.view');
   Route::post('/gstr1-detail', [GstR1Controller::class, 'gstr1Detail'])->name('gstr1-detail');
   Route::get('/gstr3b/view', [GSTR3BController::class, 'index'])->name('gstr3B.view');
   Route::get('/report/filter/3b', [GSTR3BController::class, 'filterform'])->name('report.filter.data.3b');
   Route::get('/gstr3b/view/outwarddetails', [GSTR3BController::class, 'OutwardDetails'])->name('OutwardDetails.view');
   Route::get('/gstr3b/view/itcdetails', [GSTR3BController::class, 'itcDetails'])->name('itcDetails.view');
   Route::get('/settings', [SettingsController::class, 'index'])->name('viewSettings');
   Route::post('/gstr1/send-to-gstmaster', [Gstr1Controller::class, 'sendGstr1ToGSTMaster'])->name('gstr1.send');
   Route::get('debit-note-import-view', [PurchaseReturnController::class, 'debitNoteImportView'])->name('debit-note-import-view');
   Route::post('debit-note-import-process', [PurchaseReturnController::class, 'debitNoteImportProcess'])->name('debit-note-import-process');
   Route::get('credit-note-import-view', [SalesReturnController::class, 'creditNoteImportView'])->name('credit-note-import-view');
   Route::post('credit-note-import-process', [SalesReturnController::class, 'creditNoteImportProcess'])->name('credit-note-import-process');
   Route::get('import-stock-transfer-view', [StockTransferController::class, 'importStockTransferView'])->name('import-stock-transfer-view');
   Route::post('import-stock-transfer-process', [StockTransferController::class, 'importStockTransferProcess'])->name('import-stock-transfer-process');
   Route::Resource('supplier', SupplierController::class);
   Route::post('get-supplier-location', [SupplierController::class, 'getSupplierLocation'])->name('get-supplier-location');
   Route::post('store-supplier-location', [SupplierController::class, 'storeSupplierLocation'])->name('store-supplier-location');
   Route::get('manage-supplier-rate/{date?}', [SupplierRateLocationWiseController::class, 'manageSupplierRate'])->name('manage-supplier-rate');
   Route::POST('store-supplier-rate', [SupplierRateLocationWiseController::class, 'storeSupplierRate'])->name('store-supplier-rate');
   Route::get('manage-supplier-purchase', [SupplierPurchaseController::class, 'manageSupplierPurchase'])->name('manage-supplier-purchase');
   Route::post('get-supplier-rate-by-location', [SupplierPurchaseController::class, 'getSupplierRateByLocation'])->name('get-supplier-rate-by-location');
   ('manage-supplier-purchase');
   Route::post('store-supplier-purchase-report', [SupplierPurchaseController::class, 'storeSupplierPurchaseReport'])->name('store-supplier-purchase-report');
   Route::get('complete-supplier-purchase/{id?}', [SupplierPurchaseController::class, 'completeSupplierPurchase'])->name('complete-supplier-purchase');
   Route::get('manage-supplier-purchase-report/{id?}/{from_date?}/{to_date?}', [SupplierPurchaseController::class, 'manageSupplierPurchaseReport'])->name('manage-supplier-purchase-report');
   Route::post('view-complete-purchase-info/{id?}', [SupplierPurchaseController::class, 'viewCompletePurchaseInfo'])->name('view-complete-purchase-info');
   Route::post('get-location-by-supplier', [SupplierPurchaseController::class, 'getLocationBySupplier'])->name('get-location-by-supplier');
   Route::Resource('supplier-sub-head', SupplierSubHeadController::class);
   Route::post('store-rate-difference', [SupplierController::class, 'storeRateDifference'])->name('store-rate-difference');
   Route::post('rate-by-location', [SupplierRateLocationWiseController::class, 'rateByLocation'])->name('rate-by-location');
   Route::post('get-supplier-bonus', [SupplierController::class, 'getSupplierBonus'])->name('get-supplier-bonus');
   Route::post('reset-supplier-bonus', [SupplierController::class, 'resetSupplierBonus'])->name('reset-supplier-bonus');
   Route::post('update-supplier-purchase-report', [SupplierPurchaseController::class, 'updateSupplierPurchaseReport'])->name('update-supplier-purchase-report');
   Route::post('upload-purchase-image', [SupplierPurchaseController::class, 'uploadPurchaseImage'])->name('upload-purchase-image');
   Route::get('pending-for-approval', [SupplierPurchaseController::class, 'pendingForApproval'])->name('pending-for-approval');
   Route::post('reject-purchase-report', [SupplierPurchaseController::class, 'rejectPurchaseReport'])->name('reject-purchase-report');
   Route::post('approve-purchase-report', [SupplierPurchaseController::class, 'approvePurchaseReport'])->name('approve-purchase-report');
   Route::get('view-approved-purchase-detail/{id?}/{from_date?}/{to_date?}', [SupplierPurchaseController::class, 'viewApprovedPurchaseDetail'])->name('view-approved-purchase-detail');
   Route::post('perform-action-on-purchase', [SupplierPurchaseController::class, 'performActionOnPurchase'])->name('perform-action-on-purchase');
   Route::post('store-turnover', [gstR1Controller::class, 'storeTurnOver'])->name('store-turnover');
   Route::get('manage-purchase-info', [SupplierPurchaseController::class, 'managePurchaseInfo'])->name('manage-purchase-info');
   Route::get('add-purchase-info', [SupplierPurchaseController::class, 'addPurchaseInfo'])->name('add-purchase-info');
   Route::post('store-purchase-info', [SupplierPurchaseController::class, 'storePurchaseInfo'])->name('store-purchase-info');
   Route::get('edit-purchase-info/{id}', [SupplierPurchaseController::class, 'editPurchaseInfo'])->name('edit-purchase-info');
   Route::post('update-purchase-info/{id}', [SupplierPurchaseController::class, 'updatePurchaseInfo'])->name('update-purchase-info');
   Route::post('delete-purchase-info', [SupplierPurchaseController::class, 'deletePurchaseInfo'])->name('delete-purchase-info');
   Route::post('item-by-group', [SupplierPurchaseController::class, 'itemByGroup'])->name('item-by-group');
   Route::get('supplier-purchase-setting', [SupplierPurchaseController::class, 'supplierPurchaseSetting'])->name('supplier-purchase-setting');
   Route::post('store-supplier-purchase-setting', [SupplierPurchaseController::class, 'storeSupplierPurchaseSetting'])->name('store-supplier-purchase-setting');
   Route::post('accounts-by-group', [SupplierPurchaseController::class, 'getAccountsByGroup']); 

   
   Route::get('/sale-order', [SaleOrderController::class, 'index'])->name('sale-order.index');
   Route::get('sale-order/settings', [SaleOrderController::class, 'saleOrderSetting'])->name('sale-order.settings');
   Route::post('sale-order/settings/update', [SaleOrderController::class, 'updateSaleOrderSettings'])->name('sale-order.settings.update');
   Route::Resource('sale-order', SaleOrderController::class);
   Route::post('/check-duplicate-voucher', [PurchaseController::class, 'checkDuplicateVoucher'])->name('check.duplicate.voucher');
   Route::get('sale-order-start/{id}', [SaleOrderController::class, 'saleOrderStart'])->name('sale-order-start');
   //Manage Deal Route
   Route::Resource('deal', DealController::class);
   //Fuel Supplier Route
   Route::Resource('fuel-supplier', FuelSupplierController::class);
   Route::post('store-fuel-item-rate', [FuelSupplierController::class, 'storeFuelItemRate'])->name('store-fuel-item-rate');
   Route::post('fuel_price-by-item', [FuelSupplierController::class, 'fuelPriceByItem'])->name('fuel_price-by-item');
   Route::post('get-supplier-rate-by-item', [FuelSupplierController::class, 'getSupplierRateByItem'])->name('get-supplier-rate-by-item');


   Route::get('/Salesbook', [SaleRegisterController::class, 'index'])->name('salebook.index');
   Route::get('/Purchasebook', [PurchaseRegisterController::class, 'index'])->name('purchasebook.index');
     Route::post('/get-deals-by-party', [DealController::class, 'getDealsByParty']);
Route::post('/get-deal-details', [DealController::class, 'getDealDetails']);

   //Production Route
   Route::get('/production.set_item', [ProductionController::class, 'setItems'])->name('production.set_item');
   Route::get('/production.set_item/add', [ProductionController::class, 'addItem'])->name('production.set_item.create');
   Route::post('/production.set_item/store', [ProductionController::class, 'storeItem'])->name('production.set_item.store');
   Route::get('/production.set_item/edit/{id}', [ProductionController::class, 'editItem'])->name('production.set_item.edit');
   Route::put('/production.set_item/update/{id}', [ProductionController::class, 'updateItem'])->name('production.set_item.update');
   Route::delete('/production.set_item/delete/{id}', [ProductionController::class, 'destroyItem'])->name('production.set_item.destroy');
   
   Route::Resource('deckle-process', ProductionController::class);
   Route::post('deckle-process.add_quality', [ProductionController::class, 'addQuality'])->name('deckle-process.add_quality');
   Route::post('stop-deckle-process', [ProductionController::class, 'stopDeckleProcess'])->name('stop-deckle-process');
   Route::post('stop-deckle-machine', [ProductionController::class, 'stopDeckleMachine'])->name('stop-deckle-machine');
   Route::post('start-deckle-machine', [ProductionController::class, 'startDeckleMachine'])->name('start-deckle-machine');
   
});