@extends('layouts.app')
@section('content')
@include('layouts.header')

<div class="list-of-view-company">
    <section class="list-of-view-company-section container-fluid">
        <div class="row vh-100">
            @include('layouts.leftnav')
            <div class="col-md-12 ml-sm-auto col-lg-10 px-md-4 bg-mint"> 
                @if(session('error'))
                    <div class="alert alert-danger">{{ session('error') }}</div>
                @endif
                @if(session('success'))
                    <div class="alert alert-success">{{ session('success') }}</div>
                @endif
                <div class="position-relative table-title-bottom-line d-flex justify-content-between align-items-center bg-plum-viloet title-border-redius border-divider shadow-sm py-2 px-4">
                    <h5 class="table-title m-0 py-2">Track Reel</h5>
                </div>
                <div class="bg-white p-4 shadow-sm border-radius-8">
                    <form action="{{ route('reel.info') }}" method="POST" enctype="multipart/form-data"> 
                        @csrf
                        <div class="item-section border rounded p-3 mb-3 position-relative">
                            <div class="row">
                                <div class="col-md-3 mb-3">
                                    <label>Reel No *</label>
                                    <input type="number" id="reel_no" name="reel_no" class="form-control" required placeholder="Enter Reel No">
                                </div> 
                            </div>
                        </div>
                        <div class="text-end mt-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                    @isset($reels)
                        <table class="table table-bordered mt-4">
                            <thead>
                                <tr>
                                    <th>Reel No</th>
                                    <th>Item Name</th>
                                    <th>Size</th>
                                    <th>Weight</th>
                                    <th>Created Date</th>
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>Consumption By</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($reels as $reel)
                                    <tr>
                                        <td>{{ $reel->reel_no }}</td>
                                        <td>{{ $reel->item_name }}</td>
                                        <td>{{ $reel->size }}</td>
                                        <td>{{ $reel->weight }}</td>
                                        <td>{{ date('d-m-Y H:i:s', strtotime($reel->created_at)) }}</td>
                                        <td> @if($reel->status) Available @else Not Available @endif </td>
                                        <td>
                                            @if($reel->deckle_no!="")
                                                Deckle No - {{ $reel->deckle_no }}
                                            @elseif($reel->sj_generated_voucher!="")
                                                <a href="{{ URL::to('edit-stock-journal/' . $reel->sj_generated_id) }}" target="_blank">Stock Journal - {{ $reel->sj_generated_voucher }}</a>
                                            @else
                                                N/A
                                            @endif 
                                        </td>
                                        <td>
                                            @if($reel->voucher_no_prefix!="")
                                                <a href="{{ url('sale-invoice/' . $reel->sale_id) }}" target="_blank">Sale - {{ $reel->voucher_no_prefix }}</a>
                                            @elseif($reel->sj_consumption_voucher!="")
                                                <a href="{{ URL::to('edit-stock-journal/' . $reel->sj_consumption_id) }}" target="_blank">Stock Journal - {{ $reel->sj_consumption_voucher }}</a>
                                            @else
                                                N/A
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                    @endisset
                </div>
            </div>
        </div>
    </section>
</div>

@include('layouts.footer')
<script>

</script>

@endsection
